spring:
  application:
    name: zuul-server
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        min-idle: 1
        max-idle: 8
        max-wait: 2000

server:
  port: 1119

#prefix不要和项目名一样
zuul:
  routes:
    producer:
      path: /producer/*
      serviceId: producer
  sensitiveHeaders: #如果不配置 权限会无法传到下级服务 导致访问下级服务无权限
  #prefix: /zu
  #servlet-path: / #servlet-path默认为/zuul
  #ignored-services: producer
  #add-host-header: true
  ratelimit:
    key-prefix: spring-cloud-book #按粒度拆分的临时变量key前缀
    enabled: true
    repository: redis
    behind-proxy: true
    default-policy:
      limit: 2
      quota: 1
      refresh-interval: 3
      type:
        - user
        - orign
        - url

eureka:
  client:
    serviceUrl:
      defaultZone: http://liujie:123456@server1:8089/eureka/

management:
  endpoints:
    web:
      exposure:
        include: ["*"]

security:
  oauth2:
    client:
      access-token-uri: http://localhost:1114/uaa/oauth/token #令牌端点
      user-authorization-uri: http://localhost:1114/uaa/oauth/authorize #授权端点
      client-id: zuul_server
      client-secret: secret
    resource:
      jwt:
        key-value: springcloud123 #这里的值如果跟authserver中的JwtAccessTokenConverter不一致会导致一直重定向


