spring:
  application:
    name: zuul-server
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        min-idle: 1
        max-idle: 8
        max-wait: 2000
  profiles:
    include: database,default


# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug

server:
  port: 1119

#prefix不要和项目名一样
zuul:
  routes:
    producer:
      path: /producer/*
      serviceId: producer
  sensitiveHeaders: #如果不配置 权限会无法传到下级服务 导致访问下级服务无权限
  #prefix: /zu
  #servlet-path: / #servlet-path默认为/zuul
  #ignored-services: producer
  #add-host-header: true
  ratelimit:
     key-prefix: your-prefix
     enabled: true
     repository: REDIS
     behind-proxy: true
     add-response-headers: true
     default-policy-list: #optional - will apply unless specific policy exists
       - limit: 10 #optional - request number limit per refresh interval window
         quota: 1000 #optional - request time limit per refresh interval window (in seconds)
         refresh-interval: 60 #default value (in seconds)
         type: #optional
           - user
           - origin
           - url
           - httpmethod

eureka:
  client:
    serviceUrl:
      defaultZone: http://liujie:123456@server1:8089/eureka/

management:
  endpoints:
    web:
      exposure:
        include: ["*"]

security:
  oauth2:
    client:
      access-token-uri: http://localhost:1114/uaa/oauth/token #令牌端点
      user-authorization-uri: http://localhost:1114/uaa/oauth/authorize #授权端点
      client-id: zuul_server
      client-secret: secret
    resource:
      jwt:
        key-value: springcloud123 #这里的值如果跟authserver中的JwtAccessTokenConverter不一致会导致一直重定向

#设置zuul超时时间，serviceId方式，如果为url方式，使用zuul.host.*
ribbon:
  ReadTimeout: 60000  # 单位毫秒数
  SocketTimeout: 60000

